paths:
  html_storage: "/home/liran/Documents/data_engineering/wikipedia_etl/tests/data"  # Where your crawler saved the HTML files

mysql:
  host: "localhost"
  user: "liran"
  password: "lir109"
  database: "wikipedia_metadata"

hdfs:
  url: "http://localhost:50070"
  user: "lshunak"