services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000-9001:9000"  # Expose ports 9000 and 9001
    environment:
      FLASK_ENV: development
      API_KEY: ${API_KEY}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 9000
    depends_on:
      - db
    #scale: 2
      
  db:
    image: mysql:8.0
    container_name: weather-history
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf  # Mount custom config


volumes:
  db_data:
    driver: local
