services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    ports:
      - "9000:5000"  # Expose port 5000 from the container to port 9000 on the host
    environment:
      - PORT=5000
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    depends_on:
      - db  # Ensure db service starts before the web service

  db:
    image: mysql:5.7  # Use MySQL 5.7 image
    container_name: weather_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # MySQL root password
      MYSQL_USER: weather_user  # Custom MySQL user
      MYSQL_PASSWORD: weatherpass  # Custom password for the user
      MYSQL_DATABASE: weather_history  # Name of the database
    ports:
      - "3306:3306"  # Expose port 3306 to host machine (MySQL default)
    volumes:
      - db_data:/var/lib/mysql  # Persist database data across container restarts

volumes:
  db_data:
    driver: local
